services:
  ydb:
    image: ydbplatform/local-ydb:latest
    container_name: ydb-local
    platform: linux/amd64
    ports:
      - "2136:2136" # GRPC
      - "9092:9092"  
      - "8765:8765" # Monitoring
      - "2135:2135"  
    environment:
      GRPC_TLS_PORT: 2135
      GRPC_PORT: 2136
      MON_PORT: 8765
      YDB_KAFKA_PROXY_PORT: 9092
    volumes:
      - ydb_certs:/ydb_certs
      - ydb_data:/ydb_data
    networks:
      - app-network
  
  
  backend:
    build:
      context: ./backend
    restart: always
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - ydb
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    depends_on:
      - ydb
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - app-network
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - app-network  

volumes:
  ydb_data:
  ydb_certs:
  prometheus_data:
  grafana_data:

networks:
  app-network:
    driver: bridge