# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["ydb:8765"]

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"
  
  - job_name: "backend"
    static_configs:
      - targets: ["backend:8000"]
    scrape_interval: 1s
  
  - job_name: "ydb_dynamic"
    metrics_path: "/counters/counters=ydb/name_label=name/prometheus"
    static_configs:
      - targets: ["ydb:8765"]
        labels:
          container: ydb-local
    
    metric_relabel_configs:
      - source_labels: ["__name__"]
        target_label: "__name__"
        replacement: "ydb_$1"

    
  - job_name: "utils_dynamic"
    metrics_path: "/counters/counters=utils/prometheus"
    static_configs:
      - targets: ["ydb:8765"]
        labels:
          container: ydb-local
    
    metric_relabel_configs:
      - source_labels: ["__name__"]
        target_label: "__name__"
        replacement: "utils_$1"

  - job_name: "kqp_dynamic"
    metrics_path: "/counters/counters=kqp/prometheus"
    static_configs:
      - targets: ["ydb:8765"]
        labels:
          container: ydb-dynamic

    metric_relabel_configs:
      - source_labels: ["__name__"]
        target_label: "__name__"
        replacement: "kqp_$1"
  
  - job_name: "tablets_dynamic"
    metrics_path: "/counters/counters=tablets/prometheus"
    static_configs:
      - targets: ["ydb:8765"]
        labels:
          container: ydb-local
    
    metric_relabel_configs:
      - source_labels: ["__name__"]
        target_label: "__name__"
        replacement: "tablets_$1"
  - job_name: "proxy_dynamic"
    metrics_path: "/counters/counters=proxy/prometheus"
    static_configs:
      - targets: ["ydb:8765"]
        labels:
          container: ydb-local

  
    metric_relabel_configs:
      - source_labels: ["__name__"]
        target_label: "__name__"
        replacement: "proxy_$1"

  - job_name: "dsproxynode_dynamic"
    metrics_path: "/counters/counters=dsproxynode/prometheus"
    static_configs:
      - targets: ["ydb:8765"]
        labels:
          container: ydb-local
  
    metric_relabel_configs:
      - source_labels: ["__name__"]
        target_label: "__name__"
        replacement: "dsproxynode_$1"

  - job_name: "ic_dynamic"
    metrics_path: "/counters/counters=interconnect/prometheus"
    static_configs:
      - targets: ["ydb:8765"]
        labels:
          container: ydb-local

    metric_relabel_configs:
      - source_labels: ["__name__"]
        target_label: "__name__"
        replacement: "interconnect_$1"